import {color} from '@rneui/base';
import {Dimensions, StyleSheet} from 'react-native';
import {black} from 'react-native-paper/lib/typescript/styles/themes/v2/colors';
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from 'react-native-responsive-dimensions';

export const styles = StyleSheet.create({
  APPcontainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ECF0F1',
  },

  // Enter Password page

  containerL: {
    flex: 1,
    backgroundColor: '#2160f3',
    paddingHorizontal: 16,
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flex: 1,
    // justifyContent: 'start',
    paddingHorizontal: 10,
    paddingBottom: 30,
  },
  textEnterPassnames: {
    color: '#fff',
    fontSize: 50,
    marginVertical: 20,
    fontWeight: 'bold',
    padding: 10,
  },

  signinnames: {
    color: '#fff',
    fontSize: 40,
    marginVertical: 20,
    fontWeight: 'bold',
    padding: 10,
  },
  logoname: {
    color: '#0e161a',
    fontSize: 50,
    marginVertical: 20,
    fontWeight: 'bold',
  },
  emailloginname: {
    color: '#fff',
    fontSize: 15,
    marginVertical: 10,
    padding: 10,
  },
  TextEnterPassname: {
    color: '#fff',
    fontSize: 15,
    marginVertical: 10,
    padding: 10,
  },

  footer: {
    // backgroundColor: '#f0f8ff',
    // flex: 3,
    // paddingVertical: 30,
    // paddingHorizontal: 20,
    // borderRadius: 15,
  },
  text: {
    color: '#000',
    fontSize: 15,
  },
  //refreal code
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
    width: '100%',
  },
  centeredModelView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
    width: '100%',
    backgroundColor: 'rgba(18, 17, 17, 0.48)',
  },
  modalcontainer: {
    width: '100%',
  },

  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    // alignItems: "center",
    shadowColor: '#000',
    shadowOffset: {
      width: '100%',
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  mainsubmitcontainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  submitcontainer: {
    backgroundColor: '#0D6896',
    paddingVertical: 15,
    textAlign: 'center',
    borderRadius: 28,
    paddingHorizontal: 20,
    width: '48%',
  },
  submitheading: {
    textAlign: 'center',
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  refbutton: {
    borderRadius: 20,
    // padding: 10,
    // marginHorizontal:20,
    // marginRight:200
  },
  buttonOpen: {
    // backgroundColor: "#F194FF",
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: '#000',
    fontWeight: 'bold',
    fontSize: responsiveFontSize(1.8),
  },
  modalText: {},
  Refinput: {
    paddingLeft: 10,
    color: '#000',
    borderColor: '#D2D2D2',
    borderWidth: 1,
    marginTop: 2,
    marginBottom: 30,
    borderRadius: 28,
    height: 48,
    width: '100%',
  },
  //  login screen css add here
  signinput: {
    paddingLeft: 10,
    color: '#000',
    borderColor: '#6D9886',
    borderWidth: 1,
    marginTop: 2,
    marginBottom: 30,
    borderRadius: 5,
    height: 55,
  },
  loginButtonContainer: {
    backgroundColor: '#0D6896',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 8,
    width: '100%',
    borderColor: '#0D6896',
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
  },
  submitButtonContainer: {
    backgroundColor: '#dee5f5',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 8,
    marginBottom: 10,
    marginTop: 10,
    width: 150,
    borderColor: 'redssss',
    borderWidth: 1,
    // marginTop:90
  },
  cancelsubmitdiv: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  submitButtonText: {
    fontSize: 16,
    color: '#000',
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  registerButtonContainer: {
    backgroundColor: '#0D6896',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 8,
    width: '100%',
    borderColor: '#0D6896',
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
  },
  loginButtonText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
    marginBottom: 6,
  },

  //  login screen css end here
  input: {
    paddingLeft: 10,
    color: '#000',
    borderColor: '#000 !important',
    borderWidth: 1,
    padding: 8,
    marginHorizontal: 2,
    marginVertical: 20,
  },

  button: {
    paddingVertical: 5,
    padding: 5,
    marginHorizontal: 5,
    marginVertical: 20,
    marginLeft: 190,
  },
  but: {
    fontSize: 18,
    marginVertical: 10,
    marginEnd: 80,
    paddingLeft: 10,
    color: '#fff',
    padding: 220,
  },
  butR: {
    fontSize: 18,
    marginVertical: 10,
    marginEnd: 80,
    paddingLeft: 10,
    color: '#fff',
  },
  Referraltext: {
    fontSize: 18,
    marginVertical: 10,
    marginEnd: 80,
    paddingLeft: 0,
    color: '#cbcbcb',
  },
  logOutButton: {
    width: '100%',
    backgroundColor: 'transparent',
    padding: 10,
    color: '#000 !important',
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginLeft: 30,
  },
  RefCodeContainer: {
    backgroundColor: '#dee5f5',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 8,
    marginBottom: 10,
    width: 150,
    borderColor: 'red',
    borderWidth: 1,
    // marginTop:90
  },

  //Address table style
  containerTAB: {
    flex: 1,
    padding: 16,
    paddingTop: 30,
    backgroundColor: '#ffffff',
  },
  headTAB: {
    height: 50,
    backgroundColor: '#6F7BD9',
  },
  textTAB: {
    textAlign: 'center',
    fontWeight: '200',
  },
  dataWrapperTAB: {
    marginTop: -1,
  },
  rowTAB: {
    height: 40,
    backgroundColor: '#F7F8FA',
  },
  aptos: {
    width: 30,
    height: 30,
    resizeMode: 'cover',
    borderRadius: 50,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  AptosImg: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 5,
    marginLeft: 10,
    marginBottom: 10,
  },
  aptosIcon: {
    flexDirection: 'column',
    display: 'flex',
    // alignItems: 'center',
    marginTop: 10,
    marginBottom: 5,
    marginLeft: 10,
    marginBottom: 10,
  },
  inputPas: {
    color: '#0D6896',
    borderColor: '#0D6896',
    borderWidth: 1,
    width: responsiveWidth(18),
    height:responsiveHeight(7),
    margin: responsiveHeight(1),
    borderRadius: responsiveWidth(3),
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: responsiveFontSize(2),
  },
  containers: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    height: '100%',
    justifyContent: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 15,
  },
  signsButtonContainer: {
    backgroundColor: '#0D6896',
    borderRadius: responsiveWidth(10),
    width: responsiveWidth(90),
    height: responsiveHeight(7),
    marginBottom: responsiveWidth(10),
    justifyContent: 'center',
  },
  signsButtonText: {
    fontSize: responsiveFontSize(2.2),
    color: '#fff',
    fontWeight: '500',
    alignSelf: 'center',
  },
  RegiButtonContainer: {
    borderRadius: responsiveWidth(10),
    width: responsiveWidth(90),
    height: responsiveHeight(7),
    marginBottom: responsiveWidth(10),
    justifyContent: 'center',
    borderColor: '#0D6896',
    borderWidth: 1,
  },
  RegiButtonText: {
    fontSize: responsiveFontSize(2.2),
    color: '#0D6896',
    fontWeight: '500',
    alignSelf: 'center',
  },

  // containerDasboard page css
  containerDasboard: {
    flex: 1,
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  tokenpointprice: {
    backgroundColor: '#FAF8F1',
    borderRadius: 50,
    paddingHorizontal: 25,
    paddingVertical: 10,
    borderColor: '#CEE5D0',
    borderWidth: 1,
  },
  tokenimages: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pointtextcontainer: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
  },
  pricebalancecontainers: {
    paddingTop: 10,
    paddingBottom: 60,
  },
  pricebalance: {
    color: '#151617',
    fontSize: 15,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  pricebalancepoints: {
    color: '#000',
    fontSize: 13,
    marginLeft: 2,
    marginTop: 5,
  },
  pricebalancecard: {
    backgroundColor: '#F8FCFC',
    borderColor: '#DCDCDC',
    borderWidth: 1,
    borderRadius: 15,
    padding: 15,
    marginVertical: 5,
  },
  pricebalancecardtwo: {
    backgroundColor: '#EAFDFC',
    borderColor: '#BFEAF5',
    borderWidth: 1,
    borderRadius: 15,
    padding: 15,
    marginVertical: 5,
  },
  pricebalancecard3: {
    backgroundColor: '#F0EBE3',
    borderColor: '#E4DCCF',
    borderWidth: 1,
    borderRadius: 15,
    padding: 15,
    marginVertical: 5,
  },

  pricebalancecardadd: {
    backgroundColor: '#0D6896',
    // borderColor: '#EFDAD7',
    // borderWidth: 1,
    borderRadius: 15,
    padding: 15,
    marginVertical: 5,
    height: 100,
  },
  tokenaddicons: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  addwallets: {
    fontSize: 20,
    marginLeft: 10,
    fontWeight: '600',
    color: '#fff',
  },
  tokenstartlyimg: {
    width: 35,
    height: 35,
    borderRadius: 50,
    borderColor: '#D2DAFF',
    borderWidth: 2,
  },
  tokenstarly: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
  },
  tokenStarlyname: {
    color: '#151617',
    marginLeft: 10,
    fontWeight: '600',
    fontSize: 15,
  },
  tokenStarlynametwo: {
    color: '#0D6896',
    marginLeft: 10,
    fontWeight: 'bold',
    fontSize: 15,
    // textTransform: 'uppercase',
  },
  tokenStarlynamecontaoner: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  tokenvalew: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  margintops: {
    marginTop: 15,
  },
  tokennames15: {
    color: '#fff',
    fontSize: 14,
    backgroundColor: '#0D6896',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 50,
    // fontWeight:'500',
    // borderColor: '#707070',
    // borderWidth: 1,
  },

  tabsscreensdashboard: {
    paddingTop: 20,
  },

  //Tab  page css

  tokenbuttons: {
    flexDirection: 'row',
    justifyContent: 'center',
    display: 'flex',
    alignItems: 'center',
  },
  buttontokens: {
    width: '49%',
    margin: 2,
  },

  tokenButtonContainer: {
    backgroundColor: '#2160f3',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 8,
    marginBottom: 10,
    width: '100%',
    borderColor: '#2160f3',
    borderWidth: 1,
  },
  tokensButtonText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 'normal',
    alignSelf: 'center',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  collectionButtonContainer: {
    backgroundColor: '#F8EDE3',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 8,
    marginBottom: 10,
    width: '100%',
    borderColor: '#D0B8A8',
    borderWidth: 1,
  },
  collectionsButtonText: {
    fontSize: 16,
    color: '#2C3639',
    fontWeight: 'normal',
    alignSelf: 'center',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  searcing: {
    paddingTop: 10,
  },
  searcingbox: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
  },
  searcinginputbox: {
    position: 'relative',
    marginRight: 5,
  },
  searchwidth: {
    width: 280,
  },
  searchingbar: {
    backgroundColor: '#FCF8E8',
    paddingLeft: 40,
    paddingRight: 20,
    color: '#2C3639',
    borderColor: '#CEE5D0',
    borderWidth: 1,
    marginTop: 2,
    marginBottom: 20,
    borderRadius: 50,
    height: 40,
  },
  searchicons: {
    position: 'absolute',
    top: 12,
    left: 14,
  },
  iconedits: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    top: -8,
    marginLeft: 40,
  },
  editbg: {
    backgroundColor: '#0D6896',
    color: '#0D6896',
    borderColor: '#0D6896',
    borderWidth: 1,
    width: 40,
    height: 40,
    borderRadius: 50,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 5,
  },
  tokenhideparice: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  // Profile css area start
  profilescsspage: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomColor: '#BBBBBB',
    borderBottomWidth: 1,
  },
  useremails: {
    fontSize: 15,
    color: '#000',
    fontWeight: '500',
    textAlign: 'left',
  },
  menuprog: {
    paddingTop: 30,
  },
  setticons: {
    backgroundColor: '#0D6896',
    width: 40,
    height: 40,
    borderRadius: 50,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menunames: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
  },
  marginleft: {
    marginHorizontal: 10,
  },
  generalstext: {
    color: '#000',
    fontSize: 15,
    fontWeight: '600',
  },
  subtext: {
    color: '#5F6769',
    fontSize: 12,
    fontWeight: '400',
  },

  margintops: {
    marginTop: 20,
  },
  outlinesbtn: {
    marginVertical: 30,
  },

  proloutButtonText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
    alignSelf: 'center',
    marginBottom: 6,
    marginLeft: 5,
    textAlignVertical: 'top',
    // backgroundColor:'red'
  },

  logoutbutten: {
    backgroundColor: '#0D6896',
    borderRadius: 28,
    paddingVertical: 10,
    paddingHorizontal: 8,
    marginBottom: 10,

    width: '100%',
  },
  Accountnametext: {
    color: '#000',
    fontSize: 18,

    fontWeight: '600',
  },
  editProfile: {
    backgroundColor: '#0D6896',
    color: '#2C3639',
    // borderColor: '#CEE5D0',
    // borderWidth: 1,
    width: 40,
    height: 40,
    borderRadius: 50,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 5,
    marginLeft: 20,
  },
  referraltext: {
    color: '#000',
    fontSize: 18,
    fontWeight: '600',
    paddingVertical: 25,
  },
  refeeralstyle: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
  },
  refeecode: {
    backgroundColor: '#0D6896',
    color: '#fff',
    margin: 5,
    borderRadius: 5,
    paddingVertical: 8,
    paddingHorizontal: 15,
  },
  //swap page css
  swaphad: {
    flex: 1,
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  swapcontainers: {
    paddingTop: 10,
    paddingBottom: 60,
  },
  swapHAD: {
    marginHorizontal: 20,
  },
  swapHADText: {
    color: '#000',
    fontSize: 20,
    fontWeight: 'bold',
    // textTransform: 'uppercase',
  },
  swapHADTe: {
    color: '#000',
    borderColor: 5,
    marginTop: 10,
  },
  Dividerline: {
    marginVertical: 10,
  },
  swapbalancecard: {
    // backgroundColor: '#1A1B1C',
    backgroundColor: '#f1faff00',
    borderColor: '#d9d9d9',
    borderWidth: 1,
    borderRadius: 15,
    padding: 15,
    marginVertical: 5,
  },
  swaptoken: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
  },

  swaptextcontainer: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
  },
  swapStarlyname: {
    color: '#151617',
    marginLeft: 10,
    fontWeight: '500',
    fontSize: 16,
  },
  swapStarlynamecontaoner: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  swapStarlynametwo: {
    color: '#151617',
    marginLeft: 10,
    fontWeight: '500',
    fontSize: 17,
    textTransform: 'uppercase',
  },
  swapvalew: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  swapmargintops: {
    marginTop: 15,
  },
  swapnames15: {
    color: '#000',
    fontSize: 14,
    backgroundColor: '#FCF8E8',
    paddingHorizontal: 8,
    borderRadius: 50,
    borderColor: '#CEE5D0',
    borderWidth: 1,
  },

  swapicons: {
    marginBottom: 15,
    marginTop: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconswaping: {
    // backgroundColor: '#0D6896',
    // borderColor: '#88A47C',
    // borderWidth: 1,
    width: 35,
    height: 40,
  },
  bnbswap: {
    marginLeft: 0,
    color: '#fff',
  },
  BnbStyle: {},
  swapSlippage: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  Slippageswap: {
    color: 'black',
  },
  proffswap: {
    color: 'red',
  },
  swapbuttonConten: {
    marginVertical: 20,
  },
  swapButtonContainer: {
    backgroundColor: '#0D6896',
    borderRadius: 30,
    paddingVertical: 8,
    paddingHorizontal: 8,
    width: '100%',
    borderColor: '#0D6896',
    borderWidth: 1,
    justifyContent: 'center',
  },
  swapButtonText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
    alignSelf: 'center',
    marginBottom: 6,
  },
  // Staking page
  stakinghad: {
    flex: 1,
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  stakingcontainers: {
    paddingTop: 10,
    paddingBottom: 60,
  },
  StakingHAD: {
    marginHorizontal: 10,
  },
  stakingHADText: {
    color: '#2B3A55',
    fontSize: 20,
    fontWeight: 'bold',
    // textTransform: 'uppercase',
  },
  stakingHADTe: {
    color: '#000',
    borderColor: 5,
    marginTop: 10,
  },
  Stakingbalancecard: {
    backgroundColor: '#F1F6F5',
    borderColor: '#E6E2C3',
    borderWidth: 1,
    borderRadius: 15,
    padding: 15,
    marginVertical: 5,
  },
  StakingInputBox: {
    marginVertical: 20,
  },
  StakingInputBox2: {
    marginVertical: 5,
  },

  stakinginput: {
    paddingLeft: 10,
    color: '#fff',
    borderColor: '#a3a3a3a8',
    borderWidth: 1,
    marginTop: 2,
    marginBottom: 20,
    borderRadius: 5,
    height: 54,
    borderBottom: 0,
  },

  stakingbalancecard: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stakingpro: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  staking101: {
    color: '#000',
    fontSize: 16,
    backgroundColor: '#fff',
    paddingHorizontal: 8,
    borderRadius: 3,
    fontWeight: '600',
  },
  staking10: {
    color: '#000',
    fontSize: 16,
    backgroundColor: '#fff',
    paddingHorizontal: 8,
    borderRadius: 3,
    fontWeight: '600',
  },
  stakingvalew: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stakingtops: {
    marginTop: -15,
  },
  active: {
    backgroundColor: '#FFCC00',
  },
  AvailableStaking: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bnbstaking: {
    marginLeft: 10,
    color: '#FFCC00',
    fontWeight: 'bold',
  },
  StakingText: {
    color: '#fff',
    // fontSize:12,
    // fontWeight: 'bold',
    // textTransform: 'uppercase',
  },
  pickerStyle: {
    height: 40,
    width: '100%',
    color: '#344953',
    color: '#000',
    borderColor: '#6D9886',
    borderWidth: 1,
    justifyContent: 'center',
  },

  // addtoen style
  containerAddress: {
    flex: 1,
    backgroundColor: '#FEFBF6',
    paddingHorizontal: 16,
  },
  hading: {
    flexDirection: 'column',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    // marginHorizontal: 25,
    paddingTop: 20,
    // paddingBottom: 25,
  },
  TextAdd: {
    color: '#2B3A55',
    fontSize: 20,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    paddingTop: 10,
    paddingBottom: 30,
  },
  TextHading: {
    color: '#85586F',
    fontSize: 20,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  AddressInput: {
    paddingLeft: 10,
    color: '#000',
    borderColor: '#6D9886',
    borderWidth: 1,
    marginTop: 2,
    marginBottom: 30,
    borderRadius: 5,
    height: 55,
  },
  AddressText: {
    color: '#000',
    fontSize: 17,
    // fontWeight: 'bold',
    // textTransform: 'uppercase',
    paddingTop: 10,
    paddingBottom: 30,
  },
  SymbolInput: {
    paddingLeft: 10,
    color: '#000',
    borderColor: '#6D9886',
    borderWidth: 1,
    marginTop: 2,
    marginBottom: 30,
    borderRadius: 5,
    height: 55,
  },
  SymbolText: {
    color: '#000',
    fontSize: 17,
    // fontWeight: 'bold',
    // textTransform: 'uppercase',
    paddingTop: 10,
    paddingBottom: 30,
  },
  DecimalInput: {
    paddingLeft: 10,
    color: '#000',
    borderColor: '#6D9886',
    borderWidth: 1,
    marginTop: 2,
    marginBottom: 30,
    borderRadius: 5,
    height: 55,
  },
  DecimalText: {
    color: '#000',
    fontSize: 17,
    // fontWeight: 'bold',
    // textTransform: 'uppercase',
    paddingTop: 10,
    paddingBottom: 30,
  },
  Addbuteen: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 20,
    paddingBottom: 30,
  },
  CancelButtonAddresss: {
    backgroundColor: '#dee5f5',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 8,
    width: '100%',
    borderColor: '#2160f3',
    borderWidth: 1,
    // flex: 1,
    // justifyContent: 'center',
  },
  CansalButtonText: {
    fontSize: 16,
    color: '#2160f3',
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  ImportButtonAddresss: {
    backgroundColor: '#dee5f5',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 8,
    width: '100%',
    borderColor: '#2160f3',
    borderWidth: 1,
    // flex: 1,
    // justifyContent: 'center',
  },
  ImportButtonText: {
    fontSize: 16,
    color: '#2160f3',
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
    marginBottom: 6,
  },

  //news page
  newscontainers: {
    flex: 1,
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 20,
    // width:'100%'

    height: '100%',
  },
  NewsHAd: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'flex-start',
    paddingTop: 20,
    paddingBottom: 30,
  },
  iconsnews: {
    backgroundColor: '#F5F4F4',
    borderColor: '#88A47C',
    borderWidth: 1,
    width: 30,
    height: 30,
    borderRadius: 60,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: 20,
  },
  NewsText: {
    fontSize: 20,
    color: '#000',
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  NewsTitel: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    // paddingTop: 20,
    // paddingBottom: 30,
  },
  titelText: {
    fontSize: 15,
    color: '#000',
    fontWeight: 'bold',
  },
  DataText: {
    fontSize: 15,
    color: '#E4DCCF',
    // fontWeight: 'bold',
  },
  talgramicons: {
    marginRight: 20,
  },
  icomicons: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  textNews: {
    fontSize: 15,
    color: '#2C3639',
    paddingTop: 20,
    paddingBottom: 30,
  },
  Dividerlinenews: {
    marginVertical: 20,
  },
  articleshad: {
    fontSize: 25,
    color: '#000',
    fontWeight: 'bold',
    paddingTop: 20,
    paddingBottom: 30,
  },

  Newspaper: {
    fontSize: 18,
    color: '#000',
    fontWeight: 'bold',
    paddingTop: 10,
    // paddingBottom: 10,
  },
  paperText: {
    fontSize: 15,
    color: '#3F4E4F',
    paddingTop: 0,
  },
  news: {
    paddingTop: 20,
    paddingBottom: 30,
  },
  icontwiter: {
    backgroundColor: '#F5F4F4',
    borderColor: '#88A47C',
    borderWidth: 1,
    width: 30,
    height: 30,
    borderRadius: 60,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: 20,
  },

  //Transfer page
  Transfercontainers: {
    flex: 1,
    display: 'flex',
    // alignItems: 'center',
    // height: '100%',
    // justifyContent: 'center',
    backgroundColor: '#579BB1',
    // paddingHorizontal: 16,
    paddingVertical: 20,
  },
  transfercountner: {
    backgroundColor: 'Black',
    width: '100%',
    borderWidth: 1,
    borderRadius: 15,
    padding: 15,
    marginVertical: 5,
  },
  hadingstyle: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ImageTransfer: {
    width: 50,
    height: 50,
    marginRight: 20,
    // resizeMode: 'cover',
    // borderRadius: 50,
    // overflow: 'hidden',
    // justifyContent: 'center',
    // alignItems: 'center',
  },
  transferText: {
    color: 'black',
    fontSize: 22,
    marginLeft: 35,
  },
  transferDividerline: {
    marginVertical: 40,
  },
  IconTextTransfer: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  CreateText: {
    color: 'black',
    fontSize: 15,
    marginLeft: 10,
  },
  DataTimeImagecontans: {
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  TransferImage: {
    width: 20,
    height: 20,
    resizeMode: 'cover',
    borderRadius: 50,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  IconStyle: {
    marginLeft: 20,
  },
  DataStyle: {},

  // dropdown page
  container: {
    backgroundColor: '#0D6896',
    padding: 5,
    borderWidth: 1,
    borderColor: '#DCDCDC',
    borderRadius: 28,
    marginBottom: 15,
    justifyContent: 'center',
    width: '80%',
  },

  //1st scresn line
  dotted: {
    flexDirection: 'row',
    marginTop: responsiveHeight(5),
    justifyContent: 'center',
  },
  inner: {
    height: responsiveHeight(1),
    width: responsiveWidth(2),
    margin: responsiveWidth(1),
    backgroundColor: '#BCBCBC',
    borderRadius: responsiveWidth(5),
  },
  firstcolor: {
    height: responsiveHeight(1),
    width: responsiveWidth(5),
    margin: responsiveWidth(1),
    backgroundColor: '#0D6896',
    borderRadius: responsiveWidth(5),
  },
  newsButt: {
    backgroundColor: '#0D6896',
    borderRadius: 28,
    paddingVertical: 10,
    paddingHorizontal: 30,

    width: '100%',
    justifyContent: 'center',
  },
});
